index:
   path: /
   controller: App\Controller\LandingController::index
   methods: GET
privacy-policy:
   path: /privacy-policy
   controller: App\Controller\LandingController::privacyPolicy
   methods: GET

shop:
   path: /shop
   controller: App\Controller\ProductController::shop
   methods: GET
buy-now:
   path: /purchase
   controller: App\Controller\ProductController::purchase
   methods: POST

my-library:
   path: /my-library
   controller: App\Controller\LibraryController::index
   methods: GET
upload-submit:
   path: /upload/submit
   controller: App\Controller\LibraryController::submit
   methods: POST

bookshelf:
   path: /user/{id}/bookshelf
   controller: App\Controller\BookshelfController::index
   methods: GET

# registration-form:
#    path: /register
#    controller: App\Controller\RegistrationController::index
#    methods: GET
registration-submit:
   path: /register/submit
   controller: App\Controller\RegistrationController::submit
   methods: POST
validate-email:
   path: /register/validate/email
   controller: App\Controller\RegistrationController::validateEmail
   methods: GET
registration-import:
   path: /register/import
   controller: App\Controller\RegistrationController::import
   methods: POST
registration-edit:
   path: /register/edit
   controller: App\Controller\RegistrationController::edit
   methods: POST
login-form:
   path: /login
   controller: App\Controller\LoginController::index
   methods: GET
login-submit:
   path: /login/submit
   controller: App\Controller\LoginController::submit
   methods: POST
sign-out:
   path: /sign-out
   controller: App\Controller\LoginController::signOut
   methods: GET

reset-password-form:
   path: /reset-password
   controller: App\Controller\ResetPasswordController::index
   methods: GET
send-reset-email:
   path: /reset-password/send
   controller: App\Controller\ResetPasswordController::sendResetEmail
   methods: POST
new-password:
   path: /new-password
   controller: App\Controller\ResetPasswordController::newPassword
   methods: GET
new-password-submit:
   path: /new-password/submit
   controller: App\Controller\ResetPasswordController::resetPassword
   methods: POST

login-form-admin:
   path: /admin/login
   controller: App\Controller\AdminLoginController::index
   methods: GET
login-form-admin-submit:
   path: /admin/login/submit
   controller: App\Controller\AdminLoginController::submit
   methods: POST
product-admin:
   path: /admin/products
   controller: App\Controller\ProductManagerController::index
   methods: GET
product-create:
   path: /admin/product/create
   controller: App\Controller\ProductManagerController::create
   methods: POST
product-delete:
   path: /admin/product/{id}/delete
   controller: App\Controller\ProductManagerController::delete
   methods: POST
product-edit:
   path: /admin/product/edit
   controller: App\Controller\ProductManagerController::edit
   methods: POST
book-admin:
   path: /admin/books
   controller: App\Controller\BookManagerController::index
   methods: GET
book-create:
   path: /admin/book/create
   controller: App\Controller\BookManagerController::create
   methods: POST
book-delete:
   path: /admin/book/delete
   controller: App\Controller\BookManagerController::delete
   methods: POST
book-edit:
   path: /admin/book/edit
   controller: App\Controller\BookManagerController::edit
   methods: POST
coupon-admin:
   path: /admin/coupons
   controller: App\Controller\CouponController::index
   methods: GET
coupon-create:
   path: /admin/coupon/create
   controller: App\Controller\CouponController::create
   methods: POST
export:
   path: /admin/export
   controller: App\Controller\ExportController::index
   methods: GET
dashboard:
   path: /admin/dashboard
   controller: App\Controller\DashboardController::index
   methods: GET
email-admin:
   path: /admin/email
   controller: App\Controller\AdminEmailController::index
   methods: GET
send-email-admin:
   path: /admin/email/send
   controller: App\Controller\AdminEmailController::send
   methods: POST

paypal-webhook:
   path: /webhooks/paypal
   controller: App\Controller\PaypalCallbackController::receiveEvent
   methods: POST

prospective-buyer:
   path: /admin/prospective-buyer
   controller: App\Controller\ProspectiveBuyerController::index
   methods: GET
prospective-buyer-create:
   path: /admin/prospective-buyer/create
   controller: App\Controller\ProspectiveBuyerController::create
   methods: POST